import {
  composePermutations,
  generatePermutationGroup,
  invertPermutation,
  type Permutation,
} from "./permutations";

/** A concrete subgroup: its elements, and their one-line forms as a lookup set. */
export interface Subgroup {
  elements: readonly Permutation[];
  keys: ReadonlySet<string>;
}

const keyOf = (perm: Permutation): string => perm.join(",");

/** Identifies a subgroup by its element set, independent of the order they arrived in. */
export const identityKey = (subgroup: Subgroup): string => [...subgroup.keys].sort().join("|");

/** The subgroup generated by `generators`. */
export const subgroupOf = (generators: readonly Permutation[], degree: number): Subgroup => {
  const elements = generatePermutationGroup(generators, degree);
  return { elements, keys: new Set(elements.map(keyOf)) };
};

/** `subgroup` conjugated by `by`, i.e. `by · subgroup · by⁻¹`. */
export const conjugate = (subgroup: Subgroup, by: Permutation): Subgroup => {
  const inverse = invertPermutation(by);
  const elements = subgroup.elements.map((element) =>
    composePermutations(composePermutations(by, element), inverse),
  );
  return { elements, keys: new Set(elements.map(keyOf)) };
};

/** Whether every element of `a` lies in `b`. */
export const isSubsetOf = (a: Subgroup, b: Subgroup): boolean => {
  if (a.elements.length > b.elements.length) return false;
  for (const key of a.keys) if (!b.keys.has(key)) return false;
  return true;
};

/**
 * Every subgroup, found by closing the cyclic subgroups under pairwise join.
 * Every subgroup is generated by its elements, so it is the join of the cyclic
 * subgroups it contains, and this reaches all of them.
 */
export const allSubgroups = (elements: readonly Permutation[], degree: number): Subgroup[] => {
  const cyclic = new Map<string, Subgroup>();
  for (const element of elements) {
    const subgroup = subgroupOf([element], degree);
    cyclic.set(identityKey(subgroup), subgroup);
  }

  const found = new Map(cyclic);
  let frontier = [...found.values()];
  while (frontier.length > 0) {
    const next: Subgroup[] = [];
    for (const a of frontier) {
      for (const b of cyclic.values()) {
        if (isSubsetOf(b, a)) continue;
        const joined = subgroupOf([...a.elements, ...b.elements], degree);
        const key = identityKey(joined);
        if (found.has(key)) continue;
        found.set(key, joined);
        next.push(joined);
      }
    }
    frontier = next;
  }
  return [...found.values()];
};

/** Whether `generators` generate the whole group of order `order`. */
export const generatesWholeGroup = (
  generators: readonly Permutation[],
  degree: number,
  order: number,
): boolean =>
  generators.length > 0 && generatePermutationGroup(generators, degree).length === order;
