import {
  composePermutations,
  generatePermutationGroup,
  invertPermutation,
  permutationKey,
  permutationOrder,
  type Permutation,
} from "./permutations";

/** A concrete subgroup: its elements, their one-line forms as a lookup set, and a generating set. */
export interface Subgroup {
  elements: readonly Permutation[];
  keys: ReadonlySet<string>;
  /**
   * A generating set, so that a join can close over the two generating sets
   * rather than every element of both. That is what keeps the lattice of a
   * group of order 360 affordable.
   */
  generators: readonly Permutation[];
}

const fromElements = (
  elements: readonly Permutation[],
  generators: readonly Permutation[],
): Subgroup => ({ elements, keys: new Set(elements.map(permutationKey)), generators });

/** Identifies a subgroup by its element set, independent of the order they arrived in. */
export const identityKey = (subgroup: Subgroup): string => [...subgroup.keys].sort().join("|");

/** The subgroup generated by `generators`. */
export const subgroupOf = (generators: readonly Permutation[], degree: number): Subgroup =>
  fromElements(generatePermutationGroup(generators, degree), [...generators]);

/** `subgroup` conjugated by `by`, i.e. `by · subgroup · by⁻¹`. */
export const conjugate = (subgroup: Subgroup, by: Permutation): Subgroup => {
  const inverse = invertPermutation(by);
  const image = (element: Permutation): Permutation =>
    composePermutations(composePermutations(by, element), inverse);
  return fromElements(subgroup.elements.map(image), subgroup.generators.map(image));
};

/** Whether every element of `a` lies in `b`. */
export const isSubsetOf = (a: Subgroup, b: Subgroup): boolean => {
  if (a.elements.length > b.elements.length) return false;
  for (const key of a.keys) if (!b.keys.has(key)) return false;
  return true;
};

/** The smallest subgroup containing both: the closure of their generators together. */
export const joinSubgroups = (a: Subgroup, b: Subgroup, degree: number): Subgroup =>
  subgroupOf([...a.generators, ...b.generators], degree);

/** The intersection. */
export const meetSubgroups = (a: Subgroup, b: Subgroup, degree: number): Subgroup => {
  const elements = a.elements.filter((element) => b.keys.has(permutationKey(element)));
  return fromElements(elements, minimalGeneratingSet(fromElements(elements, elements), degree));
};

/**
 * The orbit of a subgroup under conjugation by the group's generators — its
 * conjugacy class, reached by applying the inner automorphisms one generator
 * at a time.
 */
export const conjugatesOf = (
  subgroup: Subgroup,
  groupGenerators: readonly Permutation[],
): Subgroup[] => {
  const found = new Map<string, Subgroup>([[identityKey(subgroup), subgroup]]);
  const queue = [subgroup];
  for (let i = 0; i < queue.length; i++) {
    for (const generator of groupGenerators) {
      const image = conjugate(queue[i], generator);
      const key = identityKey(image);
      if (found.has(key)) continue;
      found.set(key, image);
      queue.push(image);
    }
  }
  return [...found.values()];
};

/**
 * A small generating set: greedily the element of largest order, then any
 * element outside the closure so far, until the closure is the subgroup. Not
 * provably minimal, but one element for a cyclic subgroup and rarely more
 * than needed otherwise, which is what the bake wants to store.
 */
export const minimalGeneratingSet = (subgroup: Subgroup, degree: number): Permutation[] => {
  const ordered = [...subgroup.elements].sort(
    (a, b) =>
      permutationOrder(b) - permutationOrder(a) ||
      permutationKey(a).localeCompare(permutationKey(b)),
  );
  const generators: Permutation[] = [];
  let closure = subgroupOf([], degree);
  for (const element of ordered) {
    if (closure.elements.length === subgroup.elements.length) break;
    if (closure.keys.has(permutationKey(element))) continue;
    generators.push(element);
    closure = subgroupOf(generators, degree);
  }
  return generators;
};

/**
 * Every subgroup, found by closing the cyclic subgroups under pairwise join.
 * Every subgroup is generated by its elements, so it is the join of the cyclic
 * subgroups it contains, and this reaches all of them.
 */
export const allSubgroups = (elements: readonly Permutation[], degree: number): Subgroup[] => {
  const cyclic = new Map<string, Subgroup>();
  for (const element of elements) {
    const subgroup = subgroupOf([element], degree);
    cyclic.set(identityKey(subgroup), subgroup);
  }

  const found = new Map(cyclic);
  let frontier = [...found.values()];
  while (frontier.length > 0) {
    const next: Subgroup[] = [];
    for (const a of frontier) {
      for (const b of cyclic.values()) {
        if (isSubsetOf(b, a)) continue;
        const joined = joinSubgroups(a, b, degree);
        const key = identityKey(joined);
        if (found.has(key)) continue;
        found.set(key, joined);
        next.push(joined);
      }
    }
    frontier = next;
  }
  return [...found.values()];
};

/** Whether `generators` generate the whole group of order `order`. */
export const generatesWholeGroup = (
  generators: readonly Permutation[],
  degree: number,
  order: number,
): boolean =>
  generators.length > 0 && generatePermutationGroup(generators, degree).length === order;
