import type { Permutation } from "@shared/mathUtils/groups/permutations";

/** A faithful permutation representation offered for a group. */
export interface CatalogueRepresentation {
  /** `perm-<degree>` for the minimal faithful one, else LMFDB's `nTt` label. */
  id: string;
  title: string;
  degree: number;
  transitive: boolean;
  generators: readonly Permutation[];
}

/**
 * How far down the subgroup listing the bake judged a lattice could be drawn.
 *
 * Baked but unread: the page computes its own lattice from the generators
 * (`computeSubgroupLattice`) rather than consulting this, so nothing downstream
 * branches on it. It stays because it is cheap to carry and re-baking is not.
 */
export type SubgroupRung = "all" | "classes" | "autclasses";

export interface CatalogueGroup {
  /** LMFDB abstract group label, e.g. `12.1`. Unique; the display name is not. */
  label: string;
  name: string;
  texName: string;
  displayName: string;
  order: number;

  /*
   * Everything below this line is baked but unread. LMFDB records these and the
   * bake copies them through, but no code on the page branches on any of them —
   * so treat them as data available to a future filter or badge, not as a
   * description of anything the page currently does.
   */
  abelian: boolean;
  cyclic: boolean;
  nilpotent: boolean;
  solvable: boolean;
  simple: boolean;
  /** Subgroup counts as LMFDB records them; the drawn lattice is computed, not these. */
  subgroups: {
    all: number;
    classes: number;
    autclasses: number;
    rung: SubgroupRung;
  };

  representations: readonly CatalogueRepresentation[];
}

/**
 * The bounds the catalogue was baked to.
 *
 * Baked but unread: written by `scripts/bake-groups.ts` so the file records what
 * it excluded, and checked for presence by `parseCatalogue`, but the page does
 * not show them anywhere.
 */
export interface CatalogueBounds {
  maxOrder: number;
  abelianMaxOrder: number;
  maxDegree: number;
  maxSubgroupsShown: number;
  maxRank: number;
  maxArrows: number;
}

export interface Catalogue {
  bounds: CatalogueBounds;
  groups: readonly CatalogueGroup[];
}

const CATALOGUE_URL = "/groups.json";

const fail = (what: string): never => {
  throw new TypeError(`Catalogue is malformed: ${what}`);
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

/**
 * Check the shape of a parsed catalogue.
 *
 * The file is generated by `scripts/bake-groups.ts` rather than supplied by
 * anyone, so this is a guard against a stale or half-written build, not against
 * hostile input — enough to fail loudly at load instead of somewhere downstream.
 */
export const parseCatalogue = (value: unknown): Catalogue => {
  if (!isRecord(value)) return fail("not an object");
  if (!isRecord(value.bounds)) return fail("no bounds");
  if (!Array.isArray(value.groups)) return fail("no groups");

  for (const group of value.groups) {
    if (!isRecord(group)) return fail("a group is not an object");
    if (typeof group.label !== "string") return fail("a group has no label");
    if (typeof group.order !== "number") return fail(`${group.label} has no order`);
    if (!Array.isArray(group.representations)) {
      return fail(`${group.label} has no representations`);
    }
    if (group.representations.length === 0) {
      return fail(`${group.label} has no representation to draw`);
    }
  }
  return value as unknown as Catalogue;
};

/** Load the baked catalogue. */
export const fetchCatalogue = async (url: string = CATALOGUE_URL): Promise<Catalogue> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Could not load the group catalogue: ${String(response.status)}`);
  }
  return parseCatalogue(await response.json());
};

/** Index by label, which is the only field guaranteed to identify a group. */
export const byLabel = (catalogue: Catalogue): Map<string, CatalogueGroup> =>
  new Map(catalogue.groups.map((group) => [group.label, group]));
