import type { Permutation } from "@shared/mathUtils/groups/permutations";

/** A faithful permutation representation offered for a group. */
export interface CatalogueRepresentation {
  /** `perm-<degree>` for the minimal faithful one, else LMFDB's `nTt` label. */
  id: string;
  title: string;
  degree: number;
  transitive: boolean;
  primitive: boolean;
  generators: readonly Permutation[];
  /**
   * A generating set for one representative of each subgroup class, written in
   * this representation and aligned with `CatalogueGroup.subgroups.classes`.
   * One element for a cyclic class, none for the trivial one.
   */
  classGenerators: readonly (readonly Permutation[])[];
}

/**
 * A conjugacy class of subgroups, as LMFDB records it. The page draws one node
 * per class and computes the class's own subgroups only when it is opened.
 */
export interface CatalogueSubgroupClass {
  /** LMFDB's short label within the group, e.g. `6.a1.a1`. */
  id: string;
  order: number;
  /** Number of conjugate subgroups in the class; `1` exactly when normal. */
  count: number;
  cyclic: boolean;
  normal: boolean;
  texName: string;
  displayName: string;
  /** Indices of the classes immediately below this one. */
  covers: readonly number[];
}

export interface CatalogueGroup {
  /** LMFDB abstract group label, e.g. `12.1`. Unique; the display name is not. */
  label: string;
  name: string;
  texName: string;
  displayName: string;
  order: number;

  /*
   * Everything from here to `subgroups` is baked but unread. LMFDB records
   * these and the bake copies them through, but no code on the page branches
   * on any of them — so treat them as data available to a future filter or
   * badge, not as a description of anything the page currently does.
   */
  abelian: boolean;
  cyclic: boolean;
  nilpotent: boolean;
  solvable: boolean;
  simple: boolean;
  solvabilityType: number;
  /** `-1` when the group is not nilpotent, as LMFDB stores it. */
  nilpotencyClass: number;
  rank: number;
  autTexName: string | null;
  autDisplayName: string | null;
  autOrder: number | null;

  subgroups: {
    /** Number of subgroups altogether, across every class. */
    all: number;
    /** Ordered by subgroup order: the trivial class first, the whole group last. */
    classes: readonly CatalogueSubgroupClass[];
  };

  representations: readonly CatalogueRepresentation[];
}

/**
 * The bounds the catalogue was baked to.
 *
 * Baked but unread: written by `scripts/bake-groups.ts` so the file records what
 * it excluded, and checked for presence by `parseCatalogue`, but the page does
 * not show them anywhere.
 */
export interface CatalogueBounds {
  maxOrder: number;
  maxSubgroupClasses: number;
  maxDegree: number;
  maxRepresentations: number;
}

export interface Catalogue {
  bounds: CatalogueBounds;
  groups: readonly CatalogueGroup[];
}

const CATALOGUE_URL = "/groups.json";

const fail = (what: string): never => {
  throw new TypeError(`Catalogue is malformed: ${what}`);
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

/**
 * Check the shape of a parsed catalogue.
 *
 * The file is generated by `scripts/bake-groups.ts` rather than supplied by
 * anyone, so this is a guard against a stale or half-written build, not against
 * hostile input — enough to fail loudly at load instead of somewhere downstream.
 */
export const parseCatalogue = (value: unknown): Catalogue => {
  if (!isRecord(value)) return fail("not an object");
  if (!isRecord(value.bounds)) return fail("no bounds");
  if (!Array.isArray(value.groups)) return fail("no groups");

  for (const group of value.groups) {
    if (!isRecord(group)) return fail("a group is not an object");
    if (typeof group.label !== "string") return fail("a group has no label");
    const label = group.label;
    if (typeof group.order !== "number") return fail(`${label} has no order`);
    if (!isRecord(group.subgroups) || !Array.isArray(group.subgroups.classes)) {
      return fail(`${label} has no subgroup classes`);
    }
    const classes: unknown[] = group.subgroups.classes;
    const last: unknown = classes[classes.length - 1];
    if (!isRecord(last) || last.order !== group.order) {
      return fail(`${label}'s subgroup classes do not end at the whole group`);
    }
    if (!Array.isArray(group.representations)) {
      return fail(`${label} has no representations`);
    }
    if (group.representations.length === 0) {
      return fail(`${label} has no representation to draw`);
    }
    for (const representation of group.representations) {
      if (
        !isRecord(representation) ||
        !Array.isArray(representation.classGenerators) ||
        representation.classGenerators.length !== classes.length
      ) {
        return fail(`${label} has a representation without generators for every class`);
      }
    }
  }
  return value as unknown as Catalogue;
};

/** Load the baked catalogue. */
export const fetchCatalogue = async (url: string = CATALOGUE_URL): Promise<Catalogue> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Could not load the group catalogue: ${String(response.status)}`);
  }
  return parseCatalogue(await response.json());
};

/** Index by label, which is the only field guaranteed to identify a group. */
export const byLabel = (catalogue: Catalogue): Map<string, CatalogueGroup> =>
  new Map(catalogue.groups.map((group) => [group.label, group]));
