import type { Permutation } from "@shared/permutations";

/** A faithful permutation representation offered for a group. */
export interface CatalogueRepresentation {
  /** `perm-<degree>` for the minimal faithful one, else LMFDB's `nTt` label. */
  id: string;
  title: string;
  degree: number;
  transitive: boolean;
  generators: readonly Permutation[];
}

/** Which subgroups the lattice can show without passing the diagram's budget. */
export type SubgroupRung = "all" | "classes" | "autclasses";

export interface CatalogueGroup {
  /** LMFDB abstract group label, e.g. `12.1`. Unique; the display name is not. */
  label: string;
  name: string;
  texName: string;
  displayName: string;
  order: number;
  abelian: boolean;
  cyclic: boolean;
  nilpotent: boolean;
  solvable: boolean;
  simple: boolean;
  subgroups: {
    all: number;
    classes: number;
    autclasses: number;
    rung: SubgroupRung;
  };
  representations: readonly CatalogueRepresentation[];
}

/** The bounds the catalogue was baked to, so the page can say what it excludes. */
export interface CatalogueBounds {
  maxOrder: number;
  abelianMaxOrder: number;
  maxDegree: number;
  maxSubgroupsShown: number;
  maxRank: number;
  maxArrows: number;
}

export interface Catalogue {
  bounds: CatalogueBounds;
  groups: readonly CatalogueGroup[];
}

export const CATALOGUE_URL = "/groups.json";

const fail = (what: string): never => {
  throw new TypeError(`Catalogue is malformed: ${what}`);
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

/**
 * Check the shape of a parsed catalogue.
 *
 * The file is generated by `scripts/bake-groups.ts` rather than supplied by
 * anyone, so this is a guard against a stale or half-written build, not against
 * hostile input — enough to fail loudly at load instead of somewhere downstream.
 */
export const parseCatalogue = (value: unknown): Catalogue => {
  if (!isRecord(value)) return fail("not an object");
  if (!isRecord(value.bounds)) return fail("no bounds");
  if (!Array.isArray(value.groups)) return fail("no groups");

  for (const group of value.groups) {
    if (!isRecord(group)) return fail("a group is not an object");
    if (typeof group.label !== "string") return fail("a group has no label");
    if (typeof group.order !== "number") return fail(`${group.label} has no order`);
    if (!Array.isArray(group.representations)) {
      return fail(`${group.label} has no representations`);
    }
    if (group.representations.length === 0) {
      return fail(`${group.label} has no representation to draw`);
    }
  }
  return value as unknown as Catalogue;
};

/** Load the baked catalogue. */
export const fetchCatalogue = async (url: string = CATALOGUE_URL): Promise<Catalogue> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Could not load the group catalogue: ${String(response.status)}`);
  }
  return parseCatalogue(await response.json());
};

/** Index by label, which is the only field guaranteed to identify a group. */
export const byLabel = (catalogue: Catalogue): Map<string, CatalogueGroup> =>
  new Map(catalogue.groups.map((group) => [group.label, group]));
