/**
 * A permutation of the points `1..degree` in one-line form: `perm[i]` is the
 * image of the point `i + 1`.
 */
export type Permutation = readonly number[];

const factorial = (n: number): number => {
  let result = 1;
  for (let i = 2; i <= n; i++) result *= i;
  return result;
};

const gcd = (a: number, b: number): number => (b === 0 ? a : gcd(b, a % b));

const lcm = (a: number, b: number): number => (a / gcd(a, b)) * b;

/** The identity permutation on `degree` points. */
export const identityPermutation = (degree: number): Permutation =>
  Array.from({ length: degree }, (_, i) => i + 1);

/**
 * Decode LMFDB's integer encoding of a permutation.
 *
 * LMFDB stores permutation-representation generators (the `gens` of
 * `gps_groups.representations.Perm`) as integers rather than as cycles. The
 * integer is the zero-based index of the permutation in the lexicographic
 * ordering of all `degree!` permutations of `1..degree`, i.e. its Lehmer code
 * read in the factorial base.
 *
 * This is what LMFDB's own `WebAbstractGroup.decode_as_perm` does -- it is
 * Sage's `Permutations(n).unrank(code)`, under the same `0 <= code < n!`
 * bound. LMFDB decodes these for display too, so the encoding buys nothing
 * downstream; it is just how the column is stored.
 * https://github.com/LMFDB/lmfdb/blob/07c4985/lmfdb/groups/abstract/web_groups.py#L2004
 */
export const decodePermutation = (index: number, degree: number): Permutation => {
  if (!Number.isInteger(index) || index < 0 || index >= factorial(degree)) {
    throw new RangeError(`Permutation index ${index} is out of range for degree ${degree}`);
  }
  const available = Array.from({ length: degree }, (_, i) => i + 1);
  const image: number[] = [];
  let remaining = index;
  let block = factorial(degree - 1);
  for (let position = degree - 1; position >= 0; position--) {
    const choice = Math.floor(remaining / block);
    remaining %= block;
    image.push(...available.splice(choice, 1));
    if (position > 0) block /= position;
  }
  return image;
};

/** Composition `a ∘ b`: apply `b` first, then `a`. */
export const composePermutations = (a: Permutation, b: Permutation): Permutation =>
  b.map((point) => a[point - 1]);

/** The nontrivial cycles of `perm`, each listed from its smallest point. */
export const permutationCycles = (perm: Permutation): number[][] => {
  const seen = new Set<number>();
  const result: number[][] = [];
  for (let start = 1; start <= perm.length; start++) {
    if (seen.has(start)) continue;
    seen.add(start);
    const cycle = [start];
    for (let point = perm[start - 1]; point !== start; point = perm[point - 1]) {
      seen.add(point);
      cycle.push(point);
    }
    if (cycle.length > 1) result.push(cycle);
  }
  return result;
};

/** Cycle notation, e.g. `(1 2 3)(4 5)`. The identity renders as `()`. */
export const formatPermutation = (perm: Permutation): string => {
  const cycles = permutationCycles(perm);
  if (cycles.length === 0) return "()";
  return cycles.map((cycle) => `(${cycle.join(" ")})`).join("");
};

/** Multiplicative order of `perm`, the lcm of its cycle lengths. */
export const permutationOrder = (perm: Permutation): number =>
  permutationCycles(perm).reduce((order, cycle) => lcm(order, cycle.length), 1);

/**
 * Orbits of the group generated by `generators`, each sorted ascending and the
 * whole list ordered by smallest point. A representation is transitive exactly
 * when this returns a single orbit.
 */
export const permutationOrbits = (
  generators: readonly Permutation[],
  degree: number,
): number[][] => {
  const assigned = new Set<number>();
  const orbits: number[][] = [];
  for (let start = 1; start <= degree; start++) {
    if (assigned.has(start)) continue;
    assigned.add(start);
    const orbit = [start];
    for (let i = 0; i < orbit.length; i++) {
      for (const generator of generators) {
        const image = generator[orbit[i] - 1];
        if (!assigned.has(image)) {
          assigned.add(image);
          orbit.push(image);
        }
      }
    }
    orbits.push([...orbit].sort((a, b) => a - b));
  }
  return orbits;
};

/**
 * Every element of the group generated by `generators`, identity first.
 * Breadth-first closure under left multiplication.
 */
export const generatePermutationGroup = (
  generators: readonly Permutation[],
  degree: number,
): Permutation[] => {
  const start = identityPermutation(degree);
  const found = new Set<string>([start.join(",")]);
  const elements: Permutation[] = [start];
  for (let i = 0; i < elements.length; i++) {
    for (const generator of generators) {
      const product = composePermutations(generator, elements[i]);
      const key = product.join(",");
      if (!found.has(key)) {
        found.add(key);
        elements.push(product);
      }
    }
  }
  return elements;
};
